### ISSUE TITLE
Ice::OperationNotExistException

### ISSUE THREAD

**Issue by kiu** [Astraalivankila/Update-Mumble-Server-Certificates#2]
Any idea why this happens?
$ murmurd -version
<F>2017-02-05 03:49:44.785 murmurd -- 1.2.18-1~ppa1~trusty1

$ ./reload_mumble_cert.py
Using default settings.
Import ice... Done
Trying to retrieve slice dynamically from server... Success
Import dynamically compiled murmur class... Done
Establish ice connection... Done
Murmur object accessible via 'mice.murmur' or 'mice.m'
1 booted servers in 'mice.sl', 'mice.s' contains 's/1 -t -e 1.0:tcp -h 127.0.0.1 -p 6502'
--- Reached interactive mode ---
Traceback (most recent call last):
  File "./reload_mumble_cert.py", line 23, in <module>
    s1.updateCertificate(certS, keyS, passphrase)
AttributeError: 'ServerPrx' object has no attribute 'updateCertificate'

When I force an up-to-date Murmur.ice file:
$ ./reload_mumble_cert.py
Using default settings.
Import ice... Done
Trying to retrieve slice dynamically from server... Failed
function takes at most 2 arguments (3 given)
Load slice (Murmur.ice)... Done
Import dynamically compiled murmur class... Done
Establish ice connection... Done
Murmur object accessible via 'mice.murmur' or 'mice.m'
1 booted servers in 'mice.sl', 'mice.s' contains 's/1 -t -e 1.0:tcp -h 127.0.0.1 -p 6502'
--- Reached interactive mode ---
Traceback (most recent call last):
  File "./reload_mumble_cert.py", line 24, in <module>
    s1.updateCertificate(certS, keyS, passphrase)
  File "Murmur.ice", line 3766, in updateCertificate
    
Ice.OperationNotExistException: exception ::Ice::OperationNotExistException
{
    id = 
    {
        name = 1
        category = s
    }
    facet = 
    operation = updateCertificate
}

**Comment by kiu** [comment]
Only available in 1.3.x
